---
title: "reading_data_from_the_web.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
```

Read in NSDUH data

```{r}
##First put in url
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)


tabl_marj <- (drug_use_xml %>% html_nodes(css = "table")) %>% 
  .[[1]] %>%  ## Handy way to access items from a list
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()

```

# Harry potter Data

```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```


```{r}
hp_movie_names <-
hpsaga_html %>% 
  html_nodes(".lister-item-header a") %>% 
  html_text()

hp_movie_runtime <- 
  hpsaga_html %>% 
  html_nodes(".runtime") %>% 
  html_text()

hp_movie_money <-
  hpsaga_html %>% 
  html_nodes(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

hp_df <-
  tibble(
    title = hp_movie_names, 
    runtime = hp_movie_runtime,
    money = hp_movie_money
  )
```

## Napolean Dynamite Example

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

# Using an API 
```{r}
nyc_water_df <- 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content()
```

# Pokemon!

```{r}
poke <-
  GET("https://pokeapi.co/api/v2/pokemon/1/") %>% 
  content()

poke$name

```

